[[on-window-detected]]
    if.app-name-regex-substring = 'telegram'
    run = ['move-node-to-workspace 3']

[[on-window-detected]]
    if.app-name-regex-substring = 'nextcloud talk'
    run = ['move-node-to-workspace 3']

[[on-window-detected]]
    if.app-name-regex-substring = 'discord'
    run = ['move-node-to-workspace 3']

[[on-window-detected]]
    if.app-name-regex-substring = 'google chrome'
    run = ['move-node-to-workspace 1']

[[on-window-detected]]
    if.app-name-regex-substring = 'postman'
    run = ['move-node-to-workspace 4']

[[on-window-detected]]
    if.app-name-regex-substring = 'tableplus'
    run = ['move-node-to-workspace 4']

[[on-window-detected]]
    if.app-name-regex-substring = 'cleanmymac'
    run = ['layout floating']

[[on-window-detected]]
    if.app-name-regex-substring = 'parallels'
    run = ['move-node-to-workspace P']

[[on-window-detected]]
    if.app-name-regex-substring = 'bitwarden'
    run = ['layout floating']

[[on-window-detected]]
    if.window-title-regex-substring = 'AI Chat'
    run = ['layout floating']

[[on-window-detected]]
    if.app-name-regex-substring = 'Open WebUI'
    run = ['layout floating']
